import jsPDF from "jspdf";

export function downloadMarkdownAsPdf(opts: {
  title: string;
  markdown: string;
  filename: string;
}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const usableWidth = pageWidth - margin * 2;
  let y = margin;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("BioBloomai", margin, y);
  y += 22;
  doc.setFontSize(14);
  doc.text(opts.title, margin, y);
  y += 8;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 18;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const lines = opts.markdown.split("\n");
  for (const raw of lines) {
    if (y > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
    let line = raw.replace(/\*\*(.+?)\*\*/g, "$1").replace(/`(.+?)`/g, "$1");
    if (line.startsWith("# ")) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(15);
      line = line.slice(2);
    } else if (line.startsWith("## ")) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      line = line.slice(3);
    } else if (line.startsWith("- ") || line.startsWith("* ")) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      line = "• " + line.slice(2);
    } else if (line.startsWith("---")) {
      doc.setDrawColor(220);
      doc.line(margin, y, pageWidth - margin, y);
      y += 12;
      continue;
    } else {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
    }
    if (!line.trim()) {
      y += 8;
      continue;
    }
    const wrapped = doc.splitTextToSize(line, usableWidth);
    for (const w of wrapped) {
      if (y > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(w, margin, y);
      y += 16;
    }
  }

  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text(
    `Generated by BioBloomai • ${new Date().toLocaleString()} • For informational purposes only.`,
    margin,
    pageHeight - 24,
  );

  doc.save(opts.filename);
}
